name: CI-test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x, latest]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run test-format
            - name: Install and setup rexreplace globally
              run: |
                  npm install -g ./
                  echo "$(npm bin -g)" >> $GITHUB_PATH
                  npx rexreplace --version || echo "rexreplace not accessible via npx"
                  rexreplace --version || echo "rexreplace not accessible directly"
            - name: Run CLI tests
              run: npm run test-cli
            - run: npm test
