name: CI-test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x, latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npx yarn install
            - name: Setup rr command
              run: |
                  npm install -g ./
                  echo "$(npm bin -g)" >> $GITHUB_PATH
                  npx rexreplace --version || echo "rexreplace not accessible via npx"
                  rexreplace --version || echo "rexreplace not accessible directly"
            - run: npx yarn test-format
            - run: npm uninstall -g rexreplace && npm -g install ./ && (which rexreplace || exit 0)
            - run: npx yarn test-cli
            - run: npx yarn test
