name: CI-test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npx yarn install
            - name: Setup rr command
              run: |
                  echo 'alias rexreplace="node ./bin/rexreplace.cli.js"' >> $HOME/.bashrc
                  source $HOME/.bashrc
                  rexreplace --version || echo "RexReplace not accessible"
            - run: npx yarn test-format
            - run: npm uninstall -g rexreplace && npm -g install ./ && (which rexreplace || exit 0)
            - run: npx yarn test-cli
            - run: npx yarn test
